### ISSUE TITLE
Adjust timer placement on window resize

### ISSUE THREAD

**Issue by MikeGrace** [limes007/timebox-timer#1]
Would love to see the timer's placement adjusted when the window gets resized. Currently the placement on the window appears to be static.

**Comment by limes007** [comment]
Thank you for your feedback. This was indeed the intended behavior. I have provided a new version (1.3.0) on Firefox Addons.
Please give feedback if it works for you.

**Comment by MikeGrace** [comment]
Nice!! It works now in 1.3.0. Thank you very much.
