### ISSUE TITLE
Adjust default timebox time

### ISSUE THREAD

**Issue by MikeGrace** [limes007/timebox-timer#2]
Feature request: 
It would be nice to be able to adjust what the default timebox time is or have it utilize the last used value. This way we wouldn't have to adjust the time every time we use it. We usually use the timer multiple times in a session reusing the same amount of time for our timeboxing. Since there isn't a way that I have found to adjust the default, we have to type in the new amount of time every time we want to restart the timer. Another potential solution would be to have a restart button to just restart with the same value that was just run similar to the focus and exit button on the timer.

**Comment by limes007** [comment]
Thank you for these ideas, I think they are very good. If I find some time I will implement these. This may take some time. Feel free to do it yourself and make a pull request.

**Comment by limes007** [comment]
I published a new version (1.4.0) which remembers the last used timebox and has an restart button also. Enjoy.
