### ISSUE TITLE
2 Issues - Adds 30 mins & Gets sticky when clicked to move

### ISSUE THREAD

**Issue by kashyap-sh** [limes007/timebox-timer#3]
1. The timer has a default value of 30 mins. SO add any time and it would start at 30+those minutes
2. Try moving the widget, it just gets stuck to the mouse and follows the mouse everywhere without staying at its new location

**Comment by limes007** [comment]
@kashyap-sh 

1) What do you mean by 1? Please explain, I don't get it. Is this a feature request?

2) I cannot reproduce the problem. What browser version and operating system are you using? Does this problem occur on every website?

**Comment by kashyap-sh** [comment]
@limes007 
1. Please find attached the video snip [here](https://www.mediafire.com/file/9ie8913rguwbdev/Issue1.webm/file). The timer basically starts at 30 mins instead of 0.
2. I use Firefox 117.0 (64-bit) on Windows 11. But I noticed that this occurs only on some pages. Particularly Moodle pages. Video [here ](https://www.mediafire.com/file/mpgw7z30jg38up4/Issue2.webm/file)

**Comment by limes007** [comment]
@kashyap-sh 
Thank you, strange. I will look into it.
Issue 1 seems to be a problem with the date/time formatter, as the progress bar seems to use 2 minutes. This may depend on your browser's locale settings. 
What locale settings are you using?
What does it look like when you enter a time >9?

**Comment by limes007** [comment]
@kashyap-sh 
I published a new version (1.5.1) with revised time display. 
Could you please check if issue 1 has now been resolved for you?

**Comment by kashyap-sh** [comment]
The time display is now fixed.

Thank you so much.

________________________________

**Comment by limes007** [comment]
@kashyap-sh 
I tried to reproduce the second issue, but I cannot access the page you used in the video as it need an account. As you told that this is a Moodle page I tried to reproduce it on the Moodle Demo Page: https://school.moodledemo.net/course/view.php?id=69 (Login-Info https://school.moodledemo.net/mod/page/view.php?id=46).

Unfortunately I could not reproduce it on this side. Can you reproduce the issue on https://school.moodledemo.net/course/view.php?id=69

**Comment by limes007** [comment]
Closed due to inactivity
