### ISSUE TITLE
extension won't start

### ISSUE THREAD

**Issue by aurisnoctis** [limes007/timebox-timer#4]
@limes007 Hi Stefan, thanks for this initiative (from some years ago). Its a great idea to display a timer in a corner of Firefox, especially in video conferences.

Just fyi the extension installed from https://addons.mozilla.org/en-US/firefox/addon/timebox-timer/ will not start in Firefox 129 on Windows 10.

**Comment by limes007** [comment]
Hi @aurisnoctis. For me, the extension works fine on Firefox 129 on Windows 10.

If it does not start, it is usually a problem with the page being displayed. The timer is added to the web page to be shown, so the web page may cause some issues.

So please let me know what web page is being displayed while the timer is not starting, and please note that it will not work on an empty tab, on about:addons, or on any other tab that does not contain a web page.

**Comment by limes007** [comment]
Closed due to inactivity

**Comment by aurisnoctis** [comment]
Yes, you are totally right :+1:

I tried it directly after downloading the extension and that was here: https://addons.mozilla.org/en-US/firefox/addon/timebox-timer/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search

I tried another website and it worked. Thanks!

**Comment by limes007** [comment]
Thank you for confirming
